name: app

type: 'golang:1.14'

hooks:
  build: |
    chmod +x start.sh
    chmod +x bin/mattermost

relationships:
  database: "database:postgresql"
  search: "search:elasticsearch"

web:
  upstream:
    socket_family: tcp
    protocol: http

  commands:
    start: ./start.sh

  locations:
    '/':
      # The public directory of the application relative to its root.
      root: 'client'
      index:
        - "root.html"
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg|map|json|woff?)$:
            allow: true
        ^/robots\.txt$:
            allow: true

disk: 1024

mounts:
  'config':
    source: local
    source_path: files/config-files
  'logs':
    source: local
    source_path: files/log-files
  'data':
    source: local
    source_path: files/data-files
  'dist/files':
    source: local
    source_path: files/dist-files
  'plugins':
    source: local
    source_path: files/plugins
  'client':
    source: local
    source_path: files/client
